# Generated by Django 4.2.4 on 2023-08-07 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continuousmetricdata',
            old_name='user',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='discretemetricdata',
            old_name='user',
            new_name='test',
        ),
    ]
