# Generated by Django 4.2.4 on 2023-08-12 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_user_continuousmetricdata_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continuousmetricdata',
            old_name='dataTime',
            new_name='dateTime',
        ),
        migrations.RenameField(
            model_name='discretemetricdata',
            old_name='dataTime',
            new_name='dateTime',
        ),
        migrations.AddField(
            model_name='test',
            name='alpha',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
