# Generated by Django 4.2.4 on 2023-08-13 00:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_discretemetricdata_metric"),
    ]

    operations = [
        migrations.RenameField(
            model_name="continuousmetricdata",
            old_name="dateTime",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="discretemetricdata",
            old_name="dateTime",
            new_name="date",
        ),
    ]
