# Generated by Django 4.2.4 on 2023-08-13 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_rename_datetime_continuousmetricdata_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="continuousmetricdata",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="discretemetricdata",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
